# Generated by Django 5.2.7 on 2025-11-29 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(upload_to='images/products/')),
                ('quantity_unit', models.CharField(choices=[('Item', 'Item'), ('KG', 'KG'), ('Litre', 'Litre')], default='Item', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (Birr per unit)')),
                ('stock', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
