# Generated by Django 5.2.7 on 2025-11-30 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_product_farmer'),
        ('users', '0012_alter_farmer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impression',
            old_name='date',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.farmer'),
        ),
    ]
