# Generated by Django 5.2.7 on 2025-12-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organic',
            field=models.BooleanField(default=False),
        ),
    ]
