# Generated by Django 5.2.7 on 2025-12-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_product_organic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_available',
            field=models.BooleanField(default=False),
        ),
    ]
