# Generated by Django 6.0.1 on 2026-01-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.FloatField(),
        ),
    ]
