# Generated by Django 5.2.7 on 2025-11-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_city_state_farmer_address_farmer_city_city_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='public_name',
            new_name='name',
        ),
    ]
