# Generated by Django 5.2.7 on 2025-11-27 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_public_name_farmer_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_rf', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_date', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.farmer')),
            ],
        ),
    ]
