# Generated by Django 5.2.7 on 2025-11-27 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_farmer_account_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='text_rf',
            new_name='tx_ref',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='farmer',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
