# Generated by Django 5.2.7 on 2025-11-27 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_text_rf_subscription_tx_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='subscription',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.subscription'),
        ),
    ]
