# Generated by Django 5.2.7 on 2025-11-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_farmer_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='name',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subscription'),
        ),
    ]
