# Generated by Django 5.2.7 on 2025-11-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_farmer_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/'),
        ),
    ]
