# Generated by Django 5.2.7 on 2025-12-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_farmer_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
