# Generated by Django 5.2.7 on 2025-12-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_farmer_subscription_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
