# Generated by Django 5.2.7 on 2025-12-19 14:33

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_farmer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[users.validators.phone_number_validator]),
        ),
    ]
