# Generated by Django 6.0.1 on 2026-01-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_farmer_city_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateField(),
        ),
    ]
